services:
  aiocatalogs:
    container_name: aiocatalogs
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8787:8787'
    environment:
      - PORT=8787
    volumes:
      - ./packages:/app/packages
      - ./node_modules:/app/node_modules
